name: Validate for PR
on: push
jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13'
      - name: Get dependencies
        run: make deps
      - name: Unit tests
        run: make ci-test
      - name: Build
        run: make build
      - name: Explore environment
        run: find . | grep -v git
      - name: Acceptance tests
        run: make acceptance-test
        env:
          GO111MODULE: on
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
