name: Validate for PR
on:
  push:
    branches:
      - master
  pull_request_target:
    types: [opened, synchronize, reopened]
jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.17'
      - name: Get dependencies
        run: make deps
      - name: Unit tests
        run: make ci-test
      - name: Build
        run: make build
      - name: Acceptance tests
        run: make acceptance-test
        env:
          GO111MODULE: on
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
